name: Publish Package to npmjs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #     with:
    #       fetch-depth: 0
    #   - name: Setup Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: "lts/*"
    #   - name: Install dependencies
    #     run: npm install && npm ci
    #   - name: Release
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     run: npx semantic-release
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Auto Increment Version
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch 
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Next Release Number
        run: echo ${{ steps.versioning.outputs.version }}
      - name: Install Dependencies
        run: npm install
      - name: Start Unit Tests
        run: npm run test
      - name: Production Build
        run: npm run build
      - name: Publish to NPM
        run: npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Archive Release
      #   uses: thedoctor0/zip-release@0.7.1
      #   with:
      #     type: 'zip'
      #     filename: 'release.zip'
      #     exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Get Release Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: "Upload Release"
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v${{ steps.package-version.outputs.current-version}}"
          draft: false
          # prerelease: true
          # files: 'release.zip'
